### DISCUSSION TITLE
Running the operator in a different namespace than the runner

### DISCUSSION THREAD

**Discussion by saviogl** [kuptan/terraform-operator#30] [General]
I've deployed the operator in a different namespace (operations) from the actual Terraform resource (default). The idea was to manage centralized configuration like `git-ssh-key` and `aws` provider secret close to the operator instead of having to deploy these in all the namespaces where we would be managing Terraform resources.

This setup doesn't work as the `terraform-runner` Job can't reference the required resources:

```yaml
- kind: ConfigMap
  name: known-hosts
- kind: Secret
  name: git-ssh-key
- kind: Secret
  name: terraform-aws (provider cred)
```

which live outside of its own namespace (default). This issue is expected as K8s doesn't allow cross-namespace secret reference, but it means that currently we'd have to deploy the operator in all targeted namespaces (if this is the case the operator should document this).

Did I miss some configuration to enable this setup? If not, is worth thinking through a way of achieving it?

If the `runner` runs within the operator namespace instead this setup could work. We could just use K8s Events and Status field on the `Terraform` CRD to notify progress
